[workspace]
members = [
    "src/projects/*",
]
default-members = [
    "src/projects/hello_cargo",
    "src/projects/hello_world",
]
resolver = "2"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
