[workspace]
members = [
    "src/projects/hello_cargo",
    "src/projects/hellow_world",
    "rustlings",
]
default-members = [
    "src/projects/hello_cargo",
    "src/projects/hellow_world",
]
resolver = "2"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

