services:
  debian-trixie-slim:
    build:
      context: .
      dockerfile: Dockerfile.debian
      args:
        BASE_IMAGE: "debian"
        BASE_TAG: "trixie-slim"
    env_file:
      - .env
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}:${LOCAL_WORKSPACE_FOLDER}
      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock
    restart: unless-stopped
    tty: true
